In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import make_classification

In [4]:
x,y=make_classification(n_samples=1000,n_features=10,n_redundant=2,n_informative=8,n_classes=3)

In [5]:
df=pd.DataFrame(x)

In [6]:
df['target']=y

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,target
0,-0.789072,1.612927,-3.553460,0.563623,-1.589315,2.240301,2.554607,-1.188283,2.071757,0.137060,1
1,0.266634,3.504067,0.995382,-1.953764,0.182416,2.227382,-0.359653,1.901121,0.606137,-0.872161,2
2,0.450176,-0.241110,-2.972574,-1.592708,-3.170574,2.572964,0.703342,-2.874881,0.590301,1.746448,0
3,-1.738252,0.559996,-0.163834,-0.716687,-0.200541,-1.489373,-0.394133,-1.846624,0.115927,-2.116703,1
4,-0.324477,1.601375,-0.988059,-0.553252,0.539844,2.374384,1.183008,-0.792429,3.390193,1.074803,0

In [17]:
df.isnull().sum()

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
target    0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.3,random_state=42)

In [31]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [33]:
ada=AdaBoostClassifier(estimator=DecisionTreeClassifier(random_state=42),
    random_state=42)

In [34]:
param_grid = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 0.5, 1.0],
    "estimator__max_depth": [1, 2, 3]
}

In [35]:
from sklearn.model_selection import GridSearchCV

In [36]:
grid = GridSearchCV(
    estimator=ada,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1,verbose=1
)

In [37]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

GridSearchCV(cv=5,
             estimator=AdaBoostClassifier(estimator=DecisionTreeClassifier(random_state=42),
                                          random_state=42),
             n_jobs=-1,
             param_grid={'estimator__max_depth': [1, 2, 3],
                         'learning_rate': [0.01, 0.1, 0.5, 1.0],
                         'n_estimators': [50, 100, 200]},
             scoring='accuracy', verbose=1)

In [38]:
print(grid.best_params_)
print(grid.best_score_)

{'estimator__max_depth': 3, 'learning_rate': 1.0, 'n_estimators': 200}
0.8400000000000001

In [39]:
from sklearn.datasets import make_regression
x,y=make_regression(n_samples=1000,n_features=10,noise=0.3,random_state=42)

In [40]:
df=pd.DataFrame(x)
df['target']=y

In [41]:
df.head()

,0,1,2,3,4,5,6,7,8,9,target
0,1.575876,0.891863,-0.726774,-0.047799,-0.657035,-1.113295,-0.877617,0.994558,-0.299696,-0.761760,-62.877668
1,0.535459,1.266661,-1.779875,1.209010,-0.113158,-0.971062,1.064171,-0.555273,0.741320,-0.987523,108.458759
2,-0.686279,0.157128,0.145836,-1.432671,-0.666849,0.176190,0.585299,0.197917,-0.404362,-0.607472,-115.386644
3,0.925282,0.395914,0.676357,0.168651,1.574147,-0.117172,-0.037687,-0.345907,0.895796,-0.837381,36.672166
4,-0.558922,1.073632,1.565524,0.377212,0.132970,-1.026515,-0.065750,-0.700121,-1.523187,1.195047,131.120599

In [42]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.3,random_state=42)

In [47]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor

base_tree = DecisionTreeRegressor(random_state=42)

model = AdaBoostRegressor(
    estimator=base_tree,
    random_state=42
)

In [48]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "n_estimators": [50, 100, 200],
    "learning_rate": [0.01, 0.1, 0.5, 1.0],
    "estimator__max_depth": [1, 2, 3, 5]
}

In [49]:
grid = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring="r2",
    n_jobs=-1,
    verbose=1
)

In [50]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 48 candidates, totalling 240 fits

GridSearchCV(cv=5,
             estimator=AdaBoostRegressor(estimator=DecisionTreeRegressor(random_state=42),
                                         random_state=42),
             n_jobs=-1,
             param_grid={'estimator__max_depth': [1, 2, 3, 5],
                         'learning_rate': [0.01, 0.1, 0.5, 1.0],
                         'n_estimators': [50, 100, 200]},
             scoring='r2', verbose=1)

In [51]:
grid.best_params_

{'estimator__max_depth': 5, 'learning_rate': 1.0, 'n_estimators': 200}

In [52]:
grid.best_score_

0.8120420249760688