In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=1000,n_features=10,n_informative=7,n_redundant=3,n_classes=3,random_state=42)

In [4]:
df=pd.DataFrame(x)
df['target']=y

In [5]:
df.head()

,0,1,2,3,4,5,6,7,8,9,target
0,0.264331,-3.250622,-0.019721,-1.602598,0.768478,-0.230210,-0.149185,-0.245729,1.463887,-2.664910,2
1,-0.727257,-1.496243,-1.520554,1.813696,-2.346360,-1.586453,1.040871,0.153606,-0.725276,-0.454735,1
2,1.864316,2.855091,1.783697,-1.473471,-1.439178,1.646343,-2.314483,2.334319,3.991993,-0.444778,0
3,-0.579298,-0.579864,-0.471004,0.310128,3.089350,1.334019,-0.433157,-2.580225,-1.812563,1.041126,2
4,-0.077497,-3.047259,1.220144,0.258761,2.142871,0.372684,0.580556,0.850522,1.501803,-0.190055,2

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [7]:
x_train.shape

(700, 10)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
knn=KNeighborsClassifier()

In [10]:
from sklearn.model_selection import GridSearchCV

In [11]:
param_grid = {
    "n_neighbors": [3, 5, 7, 9, 11, 15, 21],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan", "minkowski"],
    "p": [1, 2],
    "algorithm": ["auto", "ball_tree", "kd_tree", "brute"],
    "leaf_size": [20, 30, 40, 50]
}

In [12]:
grid=GridSearchCV(estimator=knn,param_grid=param_grid,cv=5,scoring="accuracy",n_jobs=-1)

In [13]:
grid.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [20, 30, 40, 50],
                         'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [3, 5, 7, 9, 11, 15, 21], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [14]:
y_pred=grid.predict(x_test)

In [15]:
y_pred

array([2, 2, 0, 2, 1, 0, 2, 2, 1, 1, 0, 1, 0, 0, 2, 0, 2, 0, 0, 0, 2, 2,
       1, 0, 0, 0, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1,
       1, 1, 2, 0, 0, 1, 2, 0, 0, 1, 2, 2, 0, 1, 0, 1, 2, 1, 1, 2, 1, 2,
       0, 2, 1, 0, 0, 2, 2, 1, 0, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 2, 0, 1,
       1, 2, 2, 1, 0, 0, 2, 2, 0, 2, 2, 1, 2, 0, 1, 0, 1, 0, 2, 1, 2, 0,
       1, 2, 1, 1, 0, 0, 2, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 2, 2, 2, 1,
       0, 0, 2, 2, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 2, 0, 2, 2, 1,
       0, 1, 1, 0, 2, 0, 2, 2, 2, 2, 0, 1, 0, 2, 0, 2, 2, 0, 0, 0, 1, 1,
       0, 0, 0, 2, 2, 2, 0, 2, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 2, 1, 2, 2, 1, 1, 0, 0, 0, 1, 2, 1, 1, 1, 2, 1,
       1, 2, 1, 0, 1, 1, 2, 1, 1, 2, 0, 0, 0, 1, 2, 0, 0, 2, 0, 1, 2, 1,
       0, 2, 0, 2, 0, 1, 1, 0, 0, 1, 1, 0, 2, 2, 1, 2, 2, 1, 1, 0, 1, 1,
       0, 1, 0, 2, 2, 1, 1, 0, 1, 0, 2, 1, 2, 2])

In [16]:
grid.best_params_

{'algorithm': 'auto',
 'leaf_size': 20,
 'metric': 'euclidean',
 'n_neighbors': 5,
 'p': 1,
 'weights': 'distance'}

In [17]:
grid.best_score_

0.8928571428571427

In [18]:
from sklearn.metrics import *

In [19]:
accuracy_score(y_test,y_pred)

0.8766666666666667

In [21]:
from sklearn.datasets import make_regression
x,y=make_regression(n_samples=1000,n_features=10,noise=0.3,random_state=42)

In [22]:
data=pd.DataFrame(x)
data['target']=y

In [23]:
data.head()

,0,1,2,3,4,5,6,7,8,9,target
0,1.575876,0.891863,-0.726774,-0.047799,-0.657035,-1.113295,-0.877617,0.994558,-0.299696,-0.761760,-62.877668
1,0.535459,1.266661,-1.779875,1.209010,-0.113158,-0.971062,1.064171,-0.555273,0.741320,-0.987523,108.458759
2,-0.686279,0.157128,0.145836,-1.432671,-0.666849,0.176190,0.585299,0.197917,-0.404362,-0.607472,-115.386644
3,0.925282,0.395914,0.676357,0.168651,1.574147,-0.117172,-0.037687,-0.345907,0.895796,-0.837381,36.672166
4,-0.558922,1.073632,1.565524,0.377212,0.132970,-1.026515,-0.065750,-0.700121,-1.523187,1.195047,131.120599

In [24]:
from sklearn.neighbors import KNeighborsRegressor

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
knr=KNeighborsRegressor()

In [27]:
param_grid = {
    "n_neighbors": [5, 7, 9, 11, 15, 21],
    "weights": ["uniform", "distance"],
    "metric": ["euclidean", "manhattan", "minkowski"],
    "p": [1, 2],
    "algorithm": ["auto", "ball_tree", "kd_tree", "brute"],
    "leaf_size": [30, 40, 50]
}

In [34]:
grid_r=GridSearchCV(estimator=knr,param_grid=param_grid,cv=5,n_jobs=-1,scoring="neg_mean_squared_error")

In [35]:
grid_r.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsRegressor(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [30, 40, 50],
                         'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [5, 7, 9, 11, 15, 21], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='neg_mean_squared_error')

In [36]:
grid_r.best_params_

{'algorithm': 'auto',
 'leaf_size': 30,
 'metric': 'euclidean',
 'n_neighbors': 5,
 'p': 1,
 'weights': 'distance'}

In [37]:
grid_r.best_score_

-4204.858936351944

In [38]:
y_pred=grid_r.predict(x_test)

In [39]:
r2_score(y_test,y_pred)

0.7807367148187776