In [1]:

from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
x,y=make_classification(n_samples=1000,n_features=10,n_redundant=5,n_informative=5,n_classes=3,random_state=3)

In [2]:
model=LogisticRegression(multi_class='ovr',solver='lbfgs')

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [4]:
x_train.shape,y_train.shape

((700, 10), (700,))

In [5]:
model

LogisticRegression(multi_class='ovr')

In [6]:
model.fit(x_train,y_train)

C:\Users\Mcc\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(

LogisticRegression(multi_class='ovr')

In [7]:
y_pred=model.predict(x_test)

In [8]:
from sklearn.metrics import *

In [9]:
accuracy_score(y_test,y_pred)

0.6266666666666667

In [10]:
from sklearn.datasets import load_iris

In [11]:
data=load_iris()

In [12]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [13]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [14]:
import numpy as np
import pandas as pd

In [15]:
df=pd.DataFrame(data.data,columns=data.feature_names)

In [16]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [17]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [18]:
df['target']=data.target

In [19]:
df.sample()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
49,5.0,3.3,1.4,0.2,0

In [20]:
df.target.nunique()

3

In [21]:
df.target.unique()

array([0, 1, 2])

In [22]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [23]:
x

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [24]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64

In [25]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 1)

In [26]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter = 300)
classifier

LogisticRegression(max_iter=300)

In [27]:
classifier.fit(X_train, y_train)

LogisticRegression(max_iter=300)

In [28]:
y_pred = classifier.predict(X_test)

In [29]:
y_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2])

In [30]:
prob=classifier.predict_proba(X_test)

In [31]:
prob

array([[9.84756885e-01, 1.52430933e-02, 2.17110119e-08],
       [2.75828385e-01, 7.21527683e-01, 2.64393201e-03],
       [6.28307303e-03, 8.89254472e-01, 1.04462455e-01],
       [9.85522329e-01, 1.44776082e-02, 6.32455696e-08],
       [1.18098818e-06, 1.89949900e-02, 9.81003829e-01],
       [4.52451115e-03, 6.27720946e-01, 3.67754543e-01],
       [1.46978033e-04, 1.27787036e-01, 8.72065986e-01],
       [9.57856361e-01, 4.21424117e-02, 1.22679787e-06],
       [9.69596820e-01, 3.04028712e-02, 3.08634667e-07],
       [9.74403455e-06, 2.70538004e-02, 9.72936456e-01],
       [1.89794127e-02, 8.79782627e-01, 1.01237960e-01],
       [9.66525611e-01, 3.34739470e-02, 4.41808494e-07],
       [4.71940086e-06, 3.10164916e-02, 9.68978789e-01],
       [7.14680872e-03, 8.01803376e-01, 1.91049815e-01],
       [6.97670102e-03, 7.49198895e-01, 2.43824404e-01],
       [9.88113894e-01, 1.18860390e-02, 6.70431338e-08],
       [2.25070840e-02, 9.37032308e-01, 4.04606083e-02],
       [1.09511320e-02, 6.81770966e-01, 3.07277902e-01],
       [9.59495197e-01, 4.05045011e-02, 3.02286777e-07],
       [9.82103647e-01, 1.78963062e-02, 4.72244846e-08],
       [1.18287495e-02, 8.47405944e-01, 1.40765307e-01],
       [1.27894255e-02, 6.45455955e-01, 3.41754620e-01],
       [7.47929436e-04, 4.43689571e-01, 5.55562500e-01],
       [9.84523943e-01, 1.54759864e-02, 7.07545948e-08],
       [8.05176386e-06, 5.43659897e-02, 9.45625959e-01],
       [2.46210445e-02, 9.02454958e-01, 7.29239979e-02],
       [9.86679277e-01, 1.33206805e-02, 4.22832606e-08],
       [9.81927872e-01, 1.80719945e-02, 1.33884546e-07],
       [4.04538582e-03, 8.05512615e-01, 1.90441999e-01],
       [3.44085745e-04, 2.58115787e-01, 7.41540127e-01]])

In [32]:
len(prob)

30

In [33]:
len(y_pred)

30

In [34]:
np.argmax(prob[0])

np.int64(0)

In [35]:
max_prob = np.max(prob, axis=1)
print(max_prob)

[0.98475689 0.72152768 0.88925447 0.98552233 0.98100383 0.62772095
 0.87206599 0.95785636 0.96959682 0.97293646 0.87978263 0.96652561
 0.96897879 0.80180338 0.74919889 0.98811389 0.93703231 0.68177097
 0.9594952  0.98210365 0.84740594 0.64545595 0.5555625  0.98452394
 0.94562596 0.90245496 0.98667928 0.98192787 0.80551262 0.74154013]

In [36]:
min_prob = np.min(prob, axis=1)
print(min_prob)

[2.17110119e-08 2.64393201e-03 6.28307303e-03 6.32455696e-08
 1.18098818e-06 4.52451115e-03 1.46978033e-04 1.22679787e-06
 3.08634667e-07 9.74403455e-06 1.89794127e-02 4.41808494e-07
 4.71940086e-06 7.14680872e-03 6.97670102e-03 6.70431338e-08
 2.25070840e-02 1.09511320e-02 3.02286777e-07 4.72244846e-08
 1.18287495e-02 1.27894255e-02 7.47929436e-04 7.07545948e-08
 8.05176386e-06 2.46210445e-02 4.22832606e-08 1.33884546e-07
 4.04538582e-03 3.44085745e-04]