In [24]:
import numpy as np
import pandas as pd
import os

In [25]:
fake=pd.read_csv("/kaggle/input/datasets/bhavikjikadara/fake-news-detection/fake.csv")
true=pd.read_csv("/kaggle/input/datasets/bhavikjikadara/fake-news-detection/true.csv")

In [26]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [27]:
fake.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
dtypes: object(4)
memory usage: 733.9+ KB

In [28]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [29]:
true.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
dtypes: object(4)
memory usage: 669.4+ KB

In [30]:
fake.drop(columns=['subject','date'],inplace=True)

In [31]:
true.drop(columns=['subject','date'],inplace=True)

In [32]:
fake.head()

,title,text
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk..."
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ..."
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...

In [33]:
true.head()

,title,text
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...

In [34]:
fake['label']=0

In [35]:
fake.head()

,title,text,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,0

In [36]:
true['label']=1

In [37]:
true.head()

,title,text,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,1

In [38]:
data=pd.concat([true,fake],ignore_index=True)

In [39]:
data=data.reset_index(drop=True)

In [40]:
data.head()

,title,text,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,1

In [41]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44898 entries, 0 to 44897
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   44898 non-null  object
 1   text    44898 non-null  object
 2   label   44898 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

In [42]:
data.sample(10)

,title,text,label
8759,Supreme Court Justice Ginsburg 'regrets' Trump...,WASHINGTON (Reuters) - U.S. Supreme Court Just...,1
42659,BOMBSHELL: President Carter Banned Iranians Fr...,Thanks to Daniel Greenfield for digging up thi...,0
18390,White House finalizing $29 billion request for...,WASHINGTON (Reuters) - The Trump administratio...,1
14093,China's internet regulator denounces its forme...,BEIJING (Reuters) - China s internet regulator...,1
15212,UK's May picks Brexiteer to replace scandal-hi...,LONDON (Reuters) - Theresa May appointed a str...,1
10254,McConnell rules out action this year on high c...,WASHINGTON (Reuters) - Republican U.S. Senate ...,1
34761,WHOA! CHRIS MATTHEWS DEFIES Liberal Media Scri...,LOL! Chris thrill up his leg Matthews does h...,0
8417,Trump campaign manager Manafort quits after tr...,(Reuters) - Donald Trump’s U.S. presidential c...,1
5993,"ICRC, jurists join rebuke of Trump torture rem...",GENEVA (Reuters) - The International Committee...,1
19158,"As Germans clip Merkel's wings, Brussels brace...",BRUSSELS (Reuters) - Cheers from Angela Merkel...,1

In [43]:
import re
import string

In [44]:
english_punctuations = string.punctuation

In [45]:
import nltk

In [46]:
from nltk.corpus import stopwords
stopwords_en = set(stopwords.words('english'))

In [47]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

In [48]:
lemmatizer = WordNetLemmatizer()

In [50]:
# pip install rapidfuzz

In [51]:
# from rapidfuzz import process

In [52]:
from tqdm import tqdm

In [53]:
import emoji

In [54]:
nltk.download("omw-1.4")
nltk.download("punkt")
nltk.download("wordnet")

[nltk_data] Downloading package omw-1.4 to /usr/share/nltk_data...
[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /usr/share/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [55]:
data.head(2)

,title,text,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,1

In [56]:
for col in ['title','text']:
    data[col]=data[col].str.lower()

In [57]:
data.head()

,title,text,label
0,"as u.s. budget fight looms, republicans flip t...",washington (reuters) - the head of a conservat...,1
1,u.s. military to accept transgender recruits o...,washington (reuters) - transgender people will...,1
2,senior u.s. republican senator: 'let mr. muell...,washington (reuters) - the special counsel inv...,1
3,fbi russia probe helped by australian diplomat...,washington (reuters) - trump campaign adviser ...,1
4,trump wants postal service to charge 'much mor...,seattle/washington (reuters) - president donal...,1

In [58]:
pip install contractions

Collecting contractions
  Downloading contractions-0.1.73-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting textsearch>=0.0.21 (from contractions)
  Downloading textsearch-0.0.24-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting anyascii (from textsearch>=0.0.21->contractions)
  Downloading anyascii-0.3.3-py3-none-any.whl.metadata (1.6 kB)
Collecting pyahocorasick (from textsearch>=0.0.21->contractions)
  Downloading pyahocorasick-2.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (13 kB)
Downloading contractions-0.1.73-py2.py3-none-any.whl (8.7 kB)
Downloading textsearch-0.0.24-py2.py3-none-any.whl (7.6 kB)
Downloading anyascii-0.3.3-py3-none-any.whl (345 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.1/345.1 kB 10.5 MB/s eta 0:00:00
Downloading pyahocorasick-2.3.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 10.4 MB/s eta 0:00:00
Installing collected packages: pyahocorasick, anyascii, textsearch, contractions
Successfully installed anyascii-0.3.3 contractions-0.1.73 pyahocorasick-2.3.0 textsearch-0.0.24
Note: you may need to restart the kernel to use updated packages.

In [59]:
import contractions

In [60]:
for col in ['title','text']:
    data[col]=data[col].apply(lambda x: contractions.fix(x))

In [37]:
#remove urls

In [61]:
for col in ['title','text']:
    data[col]=data[col].str.replace(r"http\S+|https\S+|www\S+","",regex=True)

In [39]:
#remove punctuation

In [62]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [63]:
for col in ['title','text']:
    data[col]=data[col].str.replace(f"[{string.punctuation}]","",regex=True)

In [64]:
pip install symspellpy

Collecting symspellpy
  Downloading symspellpy-6.9.0-py3-none-any.whl.metadata (3.9 kB)
Collecting editdistpy>=0.1.3 (from symspellpy)
  Downloading editdistpy-0.2.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (6.7 kB)
Downloading symspellpy-6.9.0-py3-none-any.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 37.1 MB/s eta 0:00:0000:0100:01
Downloading editdistpy-0.2.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (168 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.3/168.3 kB 14.6 MB/s eta 0:00:00
Installing collected packages: editdistpy, symspellpy
Successfully installed editdistpy-0.2.0 symspellpy-6.9.0
Note: you may need to restart the kernel to use updated packages.

In [65]:
filename="/kaggle/input/datasets/jasonheesanglee/symspell-677/frequency_dictionary_en_82_765.txt"

In [70]:
from tqdm import tqdm
tqdm.pandas()

In [71]:
data['corrected_text'] = data['text'].progress_apply(correct_sentences)

100%|██████████| 44898/44898 [1:05:00<00:00, 11.51it/s]

In [72]:
data.head()

,title,text,label,corrected_text
0,as yous budget fight looms republicans flip th...,washington reuters the head of a conservative...,1,washington reuters the head of a conservative ...
1,yous military to accept transgender recruits o...,washington reuters transgender people will be...,1,washington reuters transgender people will be ...
2,senior yous republican senator let mr mueller ...,washington reuters the special counsel invest...,1,washington reuters the special counsel investi...
3,fbi russia probe helped by australian diplomat...,washington reuters trump campaign adviser geo...,1,washington reuters trump campaign adviser geor...
4,trump wants postal service to charge much more...,seattlewashington reuters president donald tr...,1,seattle washington reuters president donald tr...

In [73]:
data.drop(columns=['text'],inplace=True)

In [74]:
def remove_stopwords(text):
    words=text.lower().split()
    filtered=[words for word in words if word not in stopwords_en]
    return filtered

In [85]:
data.head()

,title,label,corrected_text
0,as yous budget fight looms republicans flip th...,1,"[[washington, reuters, the, head, of, a, conse..."
1,yous military to accept transgender recruits o...,1,"[[washington, reuters, transgender, people, wi..."
2,senior yous republican senator let mr mueller ...,1,"[[washington, reuters, the, special, counsel, ..."
3,fbi russia probe helped by australian diplomat...,1,"[[washington, reuters, trump, campaign, advise..."
4,trump wants postal service to charge much more...,1,"[[seattle, washington, reuters, president, don..."

In [75]:
data['corrected_text']=data['corrected_text'].apply(remove_stopwords)

In [87]:
print(type(data['corrected_text'].iloc[0]))

<class 'list'>

In [76]:
import spacy

In [80]:
nlp=spacy.load("en_core_web_sm")

In [90]:
def lemmatize_text(text):
    
    # If it's already a list → join first
    if isinstance(text, list):
        # flatten nested list if needed
        if len(text) > 0 and isinstance(text[0], list):
            text = text[0]
        text = " ".join(map(str, text))
    
    # If it's NaN
    if text is None:
        return ""
    
    # Convert to string safely
    text = str(text)

    doc = nlp(text)
    
    return " ".join(
        token.lemma_
        for token in doc
        if token.is_alpha and not token.is_stop
    )

In [93]:
data['corrected']=data['corrected_text'].progress_apply(lemmatize_text)

100%|██████████| 44898/44898 [39:38<00:00, 18.88it/s]

In [94]:
data.head()

,title,label,corrected_text,corrected
0,as yous budget fight looms republicans flip th...,1,"[[washington, reuters, the, head, of, a, conse...",washington reuters head conservative republica...
1,yous military to accept transgender recruits o...,1,"[[washington, reuters, transgender, people, wi...",washington reuters transgender people allow ti...
2,senior yous republican senator let mr mueller ...,1,"[[washington, reuters, the, special, counsel, ...",washington reuters special counsel investigati...
3,fbi russia probe helped by australian diplomat...,1,"[[washington, reuters, trump, campaign, advise...",washington reuters trump campaign adviser geor...
4,trump wants postal service to charge much more...,1,"[[seattle, washington, reuters, president, don...",seattle washington reuters president donald tr...

In [95]:
from sklearn.feature_extraction.text import CountVectorizer

In [120]:
data['label'].value_counts()

label
0    23481
1    21417
Name: count, dtype: int64

In [98]:
cv=CountVectorizer(max_features=10000,ngram_range=(1,2),min_df=3)

In [99]:
from sklearn.model_selection import train_test_split

In [100]:
x,y=data['corrected'],data['label']

In [102]:
x_bow = cv.fit_transform(x).toarray()

In [103]:
x_train,x_test,y_train,y_test=train_test_split(x_bow,y,test_size=0.3,random_state=42)

In [104]:
from sklearn.linear_model import LogisticRegression

In [105]:
clf = LogisticRegression(max_iter=2000)

In [106]:
clf.fit(x_train, y_train)

LogisticRegression(max_iter=2000)

In [107]:
y_pred = clf.predict(x_test)

In [108]:
from sklearn.metrics import accuracy_score

In [109]:
accuracy_score(y_test,y_pred)

0.9949517446176689

In [110]:
from sklearn.metrics import classification_report

In [111]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      6996
           1       0.99      1.00      0.99      6474

    accuracy                           0.99     13470
   macro avg       0.99      1.00      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [112]:
from sklearn.ensemble import RandomForestClassifier

In [113]:
rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

In [114]:
rf.fit(x_train,y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [115]:
accuracy_score(y_test,y_pred)

0.9949517446176689

In [117]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      6996
           1       0.99      1.00      0.99      6474

    accuracy                           0.99     13470
   macro avg       0.99      1.00      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [118]:
from sklearn.svm import LinearSVC
svm= LinearSVC()

In [119]:
svm.fit(x_train,y_train)
preds = svm.predict(x_test)
accuracy_score(y_test,preds)

0.9949517446176689

In [121]:
print(classification_report(y_test,preds))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      6996
           1       0.99      1.00      0.99      6474

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [122]:
from sklearn.svm import SVC

In [ ]:
svc = SVC(kernel='rbf', C=1.0, gamma='scale')  # gamma='scale' is default
svc.fit(x_train, y_train)

In [ ]:
y_pred=svc.predict(x_test)

In [ ]:
print(accuracy_score(y_test,y_pred))

In [ ]:
print(classification_report(y_test,y_pred))

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer


tf = TfidfVectorizer(max_features=10000, stop_words='english')

In [2]:
x_tf=tf.fit_transform(x).toarray()

NameError: name 'x' is not defined

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x_tf,y,test_size=0.3,random_state=42)

In [ ]:
lg_tf=clf = LogisticRegression(max_iter=2000)

In [ ]:
lg_tf.fit(x_train,y_train)

In [ ]:

accuracy_score(y_test,y_pred)

In [ ]:
print(classification_report(y_test,y_pred))

In [ ]:
rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    random_state=42,
    n_jobs=-1
)

In [ ]:
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

In [ ]:
svm= LinearSVC()
svm.fit(x_train,y_train)
preds = svm.predict(x_test)
print(accuracy_score(y_test,preds))
print(classification_report(y_test,y_pred))

In [ ]:
from gensim.models import Word2Vec